@localhost=http://localhost:3000/api/v1
@devhost=https://ai-driven-copy.onrender.com/api/v1
@prodhost=

### Health check 
GET {{localhost}}/claim-letter/health

### dev health test
GET {{devhost}}/claim-letter/health

### get all claims
GET {{localhost}}/claim-letter/list